-- resource_manifest_version "77731fab-63ca-442c-a67b-abc70f28dfa5"
resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'

ui_page "nui/ui.html"
files {
	"nui/ui.html",
	"nui/styles.css",
	"nui/scripts.js",
	"nui/debounce.min.js",
	"nui/sweetalert2.all.min.js",
	"nui/assets/blur.svg",
	-- ICONS
	"nui/assets/icons/serra.png", 
	"nui/assets/icons/furadeira.png", 
	"nui/assets/icons/mochila.png",
	"nui/assets/icons/c4.png",
	"nui/assets/icons/money.png",
	
	--Itens
	"nui/assets/icons/adubo.png",
	"nui/assets/icons/algema.png",
	"nui/assets/icons/alianca.png",
	"nui/assets/icons/bandagem.png",
	"nui/assets/icons/brinco.png",
	"nui/assets/icons/caixa.png",
	"nui/assets/icons/capuz.png",
	"nui/assets/icons/pack.png",
	"nui/assets/icons/alicate.png",
	"nui/assets/icons/isca2.png",
	"nui/assets/icons/roupas.png",
	"nui/assets/icons/carregador.png",
	"nui/assets/icons/carteira.png",
	"nui/assets/icons/colar.png",
	"nui/assets/icons/darkmoney.png",
	"nui/assets/icons/etiqueta.png",
	"nui/assets/icons/ferramentas.png",
	"nui/assets/icons/fertlilizante.png",
	"nui/assets/icons/garrafavazia.png",
	"nui/assets/icons/isca.png",
	"nui/assets/icons/lockpick.png",
	"nui/assets/icons/maquiagem.png",
	"nui/assets/icons/masterpick.png",
	"nui/assets/icons/militec.png",
	"nui/assets/icons/orgao.png",
	"nui/assets/icons/pendrive.png",
	"nui/assets/icons/perfume.png",
	"nui/assets/icons/placa.png",
	"nui/assets/icons/polvora.png",
	"nui/assets/icons/pulseira.png",
	"nui/assets/icons/rebite.png",
	"nui/assets/icons/relogio.png",
	"nui/assets/icons/sacodelixo.png",
	"nui/assets/icons/sapatos.png",
	"nui/assets/icons/tablet.png",
	"nui/assets/icons/torademadeira.png",
	"nui/assets/icons/vibrador.png",
	
	--Drinks
	"nui/assets/icons/leite.png",
	"nui/assets/icons/absinto.png",
	"nui/assets/icons/cerveja.png",
	"nui/assets/icons/conhaque.png",
	"nui/assets/icons/energetico.png",
	"nui/assets/icons/tequeila.png",
	"nui/assets/icons/whisky.png",
	
	--Meat
	"nui/assets/icons/aguia.png",
	"nui/assets/icons/cervo.png",
	"nui/assets/icons/coelho.png",
	"nui/assets/icons/comorão.png",
	"nui/assets/icons/corvo.png",
	"nui/assets/icons/coyote.png",
	"nui/assets/icons/javali.png",
	"nui/assets/icons/lobo.png",
	"nui/assets/icons/puma.png",


	--Armas
	"nui/assets/icons/adaga.png",  
	"nui/assets/icons/ak-103.png",
	"nui/assets/icons/balamedia.png",
	"nui/assets/icons/balapequena.png",
	"nui/assets/icons/balasgrandes.png",
	"nui/assets/icons/bread.png",
	"nui/assets/icons/canivete.png",
	"nui/assets/icons/cassetete.png",
	"nui/assets/icons/chavedegrifo.png",
	"nui/assets/icons/combatpistol.png",
	"nui/assets/icons/extintor.png",
	"nui/assets/icons/faca.png",
	"nui/assets/icons/fnfiveseven.png",
	"nui/assets/icons/Garrafra.png",
	"nui/assets/icons/gasolina.png",
	"nui/assets/icons/glock19.png",
	"nui/assets/icons/hkp7m10.png",
	"nui/assets/icons/lanterna.png",
	"nui/assets/icons/M-TAR.png",
	"nui/assets/icons/M1911.png",
	"nui/assets/icons/m1922.png",
	"nui/assets/icons/M4A1.png",
	"nui/assets/icons/machado.png",
	"nui/assets/icons/machadodebatalha.png",
	"nui/assets/icons/machadodepedra.png",
	"nui/assets/icons/machete.png",
	"nui/assets/icons/magnum44.png",
	"nui/assets/icons/martelo.png",
	"nui/assets/icons/Mawchado.png",
	"nui/assets/icons/MP5.png",
	"nui/assets/icons/bomb.png",
	"nui/assets/icons/laptop.png",
	"nui/assets/icons/drill.png",
	"nui/assets/icons/paraquedas.png",
	"nui/assets/icons/pedecabra.png", 
	"nui/assets/icons/pecasdearmas.png",
	"nui/assets/icons/sniffing.png",
	"nui/assets/icons/lapislazuli.png",
	"nui/assets/icons/iron.png", 
	"nui/assets/icons/crystalmeth.png",
	"nui/assets/icons/gold.png",
	"nui/assets/icons/silver.png", 
	"nui/assets/icons/diamond.png",
	"nui/assets/icons/bronze.png",
	"nui/assets/icons/ruby.png",
	"nui/assets/icons/crystal.png",
	"nui/assets/icons/ametista.png",
	"nui/assets/icons/esmeralda.png",
	"nui/assets/icons/pills.png", 
	"nui/assets/icons/pistol_ammo.png",
	"nui/assets/icons/Remington 870.png",
	"nui/assets/icons/repairkit.png",
	"nui/assets/icons/SigSauerMPX.png",
	"nui/assets/icons/sinalizador.png",
	"nui/assets/icons/SLA.png",
	"nui/assets/icons/socoingles.png",
	"nui/assets/icons/tacodebeisebol.png",
	"nui/assets/icons/tacodegolf.png",
	"nui/assets/icons/tacodesinuca.png",
	"nui/assets/icons/tazer.png",
	"nui/assets/icons/colete.png",
	"nui/assets/icons/encomenda.png",
	"nui/assets/icons/milk.png",
	"nui/assets/icons/Thompson.png",
	"nui/assets/icons/uzi.png",
	"nui/assets/icons/vodka.png",
	"nui/assets/icons/water.png",
	"nui/assets/icons/weed.png",
	"nui/assets/icons/fish.png",
	"nui/assets/icons/fish2.png",
	"nui/assets/icons/fish3.png",
	"nui/assets/icons/fish4.png",
	"nui/assets/icons/winchester22.png",		
}

client_scripts {
	-- "lib/Tunnel.lua",
	-- "lib/Proxy.lua",
	"@vrp/lib/utils.lua",
	"config.lua",
	"client.lua",
	"itemdrop/client.lua"
}

server_scripts {
	"@vrp/lib/utils.lua",
	"config.lua",
	"server.lua",
	"itemdrop/server.lua"
}
