Config = {}

Config.OpenMenu = 207 -- Key: PAGE DOWN
Config.AntiSpamCooldown = 2
Config.Language = {
    Title = "Inventário",
    PleaseWait = "Por favor aguarde ...",
    Error = "Ocorreu um problema.",
    WarningTitle = "Atenção",
    WeaponNotEquipped = "Você não tem a arma para essa munição.",
    CannotBeUsed = "Este item não pode ser usado no seu inventário",
    NotEnoughtSpace = "A pessoa não tem espaço em sua mochila",
    NoNearby = "Não há pessoas próximas",
    MochilaCheia = "Esvazie a mochila primeiro."
}

items = {}

items["maconha"] = {"drogaanim" ,0 ,0 ,0 ,"weed.png", "Usar"}
items["bombaadesiva"] = {"none" ,0 ,0 ,0 ,"bomb.png", "Usar"}
items["computador"] = {"none" ,0 ,0 ,0 ,"laptop.png", "Usar"}
items["broca"] = {"none" ,0 ,0 ,0 ,"drill.png", "Usar"}
items["roupas"] = {"none" ,0 ,0 ,0 ,"roupas.png", "Usar"}
items["encomenda"] = {"none" ,0 ,0 ,0 ,"encomenda.png", "Usar"}
items["repairkit"] = {"none" ,0 ,0 ,0 ,"repairkit.png", "Usar"}
items["serra"] = {"none" ,0 ,0 ,0 ,"serra.png", "Usar"}
items["furadeira"] = {"none" ,0 ,0 ,0 ,"furadeira.png", "Usar"}
items["c4"] = {"none" ,0 ,0 ,0 ,"c4.png", "Usar"}
items["mochila"] = {"mochila",0 ,0 ,0 , "mochila.png", "Colocar/Tirar"}
items["mochila2"] = {"mochila",0 ,0 ,0 , "mochila.png", "Colocar"}
items["mochila3"] = {"mochila", 0 ,0 ,0 , "mochila.png", "Colocar"}
items["adubo"] = {"none" ,0 ,0 ,0 ,"adubo.png", "Usar"}
items["algemas"] = {"none" ,0 ,0 ,0 ,"algema.png", "Usar"}
items["alianca"] = {"none" ,0 ,0 ,0 ,"alianca.png", "Usar"}
items["bandagem"] = {"bandagem" ,0 ,0 ,0 ,"bandagem.png", "Usar"}
items["colete"] = {"armor" ,0 ,0 ,0 ,"colete.png", "Colocar"}
items["brinco"] = {"none" ,0 ,0 ,0 ,"brinco.png", "Usar"}
items["caixa"] = {"none" ,0 ,0 ,0 ,"caixa.png", "Usar"}
items["capuz"] = {"none" ,0 ,0 ,0 ,"capuz.png", "Usar"}
items["carregador"] = {"none" ,0 ,0 ,0 ,"carregador.png", "Usar"}
items["carteira"] = {"none" ,0 ,0 ,0 ,"carteira.png", "Usar"}
items["colar"] = {"none" ,0 ,0 ,0 ,"colar.png", "Usar"}
items["cerveja"] = {"alcoolanim" ,0 ,0 ,0 ,"cerveja.png", "Beber"}
items["tequila"] = {"alcoolanim" ,0 ,0 ,0 ,"vodka.png", "Beber"}
items["vodka"] = {"alcoolanim" ,0 ,0 ,0 ,"vodka.png", "Beber"}
items["whisky"] = {"alcoolanim" ,0 ,0 ,0 ,"whisky.png", "Beber"}
items["conhaque"] = {"alcoolanim" ,0 ,0 ,0 ,"conhaque.png", "Beber"}
items["absinto"] = {"alcoolanim" ,0 ,0 ,0 ,"absinto.png", "Beber"}
items["etiqueta"] = {"none" ,0 ,0 ,0 ,"etiqueta.png", "Usar"}
items["dinheirosujo"] = {"none" ,0 ,0 ,0 ,"money.png", "Usar"}
items["ferramenta"] = {"none" ,0 ,0 ,0 ,"ferramentas.png", "Usar"}
items["fertilizante"] = {"none" ,0 ,0 ,0 ,"fert.png", "Usar"}
items["relogioroubado"] = {"none" ,0 ,0 ,0 ,"relogio.png", "Usar"}
items["pulseiraroubada"] = {"none" ,0 ,0 ,0 ,"pulseira.png", "Usar"}
items["anelroubado"] = {"none" ,0 ,0 ,0 ,"alianca.png", "Usar"}
items["colarroubado"] = {"none" ,0 ,0 ,0 ,"colar.png", "Usar"}
items["brincoroubado"] = {"none" ,0 ,0 ,0 ,"brinco.png", "Usar"}
items["carteiraroubada"] = {"none" ,0 ,0 ,0 ,"carteira.png", "Usar"}
items["carregadorroubado"] = {"none" ,0 ,0 ,0 ,"carregador.png", "Usar"}
items["tabletroubado"] = {"none" ,0 ,0 ,0 ,"tablet.png", "Usar"}
items["sapatosroubado"] = {"none" ,0 ,0 ,0 ,"sapatos.png", "Usar"}
items["vibradorroubado"] = {"none" ,0 ,0 ,0 ,"vibrador.png", "Usar"}
items["perfumeroubado"] = {"none" ,0 ,0 ,0 ,"perfume.png", "Usar"}
items["maquiagemroubada"] = {"none" ,0 ,0 ,0 ,"maquiagem.png", "Usar"}
items["garrafavazia"] = {"none" ,0 ,0 ,0 ,"garrafavazia.png", "Usar"}
items["garrafadeleite"] = {"none" ,0 ,0 ,0 ,"milk.png", "Usar"}
items["energetico"] = {"energetico" ,0 ,0 ,0 ,"energetico.png", "Usar"}
items["componenteca"] = {"none" ,0 ,0 ,0 ,"pecasdearmas.png", "Usar"}
items["componentecb"] = {"none" ,0 ,0 ,0 ,"pecasdearmas.png", "Usar"}
items["componentecc"] = {"none" ,0 ,0 ,0 ,"pecasdearmas.png", "Usar"}
items["componentecd"] = {"none" ,0 ,0 ,0 ,"pecasdearmas.png", "Usar"}
items["aco"] = {"none" ,0 ,0 ,0 ,"pecasdearmas.png", "Usar"}
items["ferro"] = {"none" ,0 ,0 ,0 ,"pecasdearmas.png", "Usar"}
items["carbono"] = {"none" ,0 ,0 ,0 ,"pecasdearmas.png", "Usar"}
items["polvora"] = {"none" ,0 ,0 ,0 ,"pecasdearmas.png", "Usar"}
items["capsula"] = {"none" ,0 ,0 ,0 ,"pecasdearmas.png", "Usar"}
items["isca"] = {"none" ,0 ,0 ,0 ,"isca.png", "Usar"}
items["reagentesdecoca"] = {"none" ,0 ,0 ,0 ,"sniffing.png", "Usar"}
items["preparodecoca"] = {"none" ,0 ,0 ,0 ,"sniffing.png", "Usar"}
items["cocaina"] = {"drogaanim" ,0 ,0 ,0 ,"sniffing.png", "Usar"}
items["reagentesdemeta"] = {"none" ,0 ,0 ,0 ,"crystalmeth.png", "Usar"}
items["preparodemeta"] = {"none" ,0 ,0 ,0 ,"crystalmeth.png", "Usar"}
items["metanfetamina"] = {"drogaanim" ,0 ,0 ,0 ,"crystalmeth.png", "Usar"}
items["bronze"] = {"none" ,0 ,0 ,0 ,"bronze.png", "Usar"}
items["ouro"] = {"none" ,0 ,0 ,0 ,"gold.png", "Usar"}
items["prata"] = {"none" ,0 ,0 ,0 ,"silver.png", "Usar"}
items["rubi"] = {"none" ,0 ,0 ,0 ,"ruby.png", "Usar"}
items["esmeralda"] = {"none" ,0 ,0 ,0 ,"esmeralda.png", "Usar"}
items["safira"] = {"none" ,0 ,0 ,0 ,"crystal.png", "Usar"}
items["diamante"] = {"none" ,0 ,0 ,0 ,"diamond.png", "Usar"}
items["ferro"] = {"none" ,0 ,0 ,0 ,"iron.png", "Usar"}
items["ametista"] = {"none" ,0 ,0 ,0 ,"ametista.png", "Usar"}
items["lapislazuli"] = {"none" ,0 ,0 ,0 ,"lapislazuli.png", "Usar"}
items["lockpick"] = {"none" ,0 ,0 ,0 ,"lockpick.png", "Usar"}
items["dourado"] = {"none" ,0 ,0 ,0 ,"fish.png", "Usar"}
items["corvina"] = {"none" ,0 ,0 ,0 ,"fish.png", "Usar"}
items["salmao"] = {"none" ,0 ,0 ,0 ,"fish2.png", "Usar"}
items["pacu"] = {"none" ,0 ,0 ,0 ,"fish2.png", "Usar"}
items["pintado"] = {"none" ,0 ,0 ,0 ,"fish3.png", "Usar"}
items["pirarucu"] = {"none" ,0 ,0 ,0 ,"fish3.png", "Usar"}
items["tilapia"] = {"none" ,0 ,0 ,0 ,"fish3.png", "Usar"}
items["tucunare"] = {"none" ,0 ,0 ,0 ,"fish4.png", "Usar"}
items["lambari"] = {"none" ,0 ,0 ,0 ,"fish4.png", "Usar"}
items["maquiagem"] = {"none" ,0 ,0 ,0 ,"maquiagem.png", "Usar"}
items["masterpick"] = {"none" ,0 ,0 ,0 ,"masterpick.png", "Usar"}
items["militec"] = {"none" ,0 ,0 ,0 ,"militec.png", "Usar"}
items["orgao"] = {"none" ,0 ,0 ,0 ,"orgao.png", "Usar"}
items["pendrive"] = {"none" ,0 ,0 ,0 ,"pendrive.png", "Usar"}
items["perfume"] = {"none" ,0 ,0 ,0 ,"perfume.png", "Usar"}
items["placa"] = {"none" ,0 ,0 ,0 ,"placa.png", "Usar"}
items["polvora"] = {"none" ,0 ,0 ,0 ,"polvora.png", "Usar"}
items["pulseira"] = {"none" ,0 ,0 ,0 ,"pulseira.png", "Usar"}
items["rebite"] = {"none" ,0 ,0 ,0 ,"rebite.png", "Usar"}
items["relogio"] = {"none" ,0 ,0 ,0 ,"relogio.png", "Usar"}
items["sacodelixo"] = {"none" ,0 ,0 ,0 ,"sacodelixo.png", "Usar"}
items["sapatos"] = {"none" ,0 ,0 ,0 ,"sapatos.png", "Usar"}
items["tablet"] = {"none" ,0 ,0 ,0 ,"tablet.png", "Usar"}
items["tora"] = {"none" ,0 ,0 ,0 ,"torademadeira.png", "Usar"}
items["vibrador"] = {"none" ,0 ,0 ,0 ,"vibrador.png", "Usar"}
items["carnedecormorao"] = {"none" ,0 ,0 ,0 ,"comorão.png", "Usar"}
items["carnedecorvo"] = {"none" ,0 ,0 ,0 ,"corvo.png", "Usar"}
items["carnedeaguia"] = {"none" ,0 ,0 ,0 ,"aguia.png", "Usar"}
items["carnedecervo"] = {"none" ,0 ,0 ,0 ,"cervo.png", "Usar"}
items["carnedecoelho"] = {"none" ,0 ,0 ,0 ,"coelho.png", "Usar"}
items["carnedecoyote"] = {"none" ,0 ,0 ,0 ,"carne.png", "Usar"}
items["carnedelobo"] = {"none" ,0 ,0 ,0 ,"coyote.png", "Usar"}
items["carnedepuma"] = {"none" ,0 ,0 ,0 ,"puma.png", "Usar"}
items["carnedejavali"] = {"none" ,0 ,0 ,0 ,"javali.png", "Usar"}
items["pills"] = {"vida" ,0 ,0 ,0 ,"pills.png", "Usar"}
------------------------------ARMAS-----------------------------------

items["wbody|WEAPON_DAGGER"] = {"weapon" ,0 ,0 ,0 ,"adaga.png", "Equipar"}
items["wbody|WEAPON_BAT"] = {"weapon" ,0 ,0 ,0 ,"tacodebeisebol.png", "Equipar"}
items["wbody|WEAPON_BOTTLE"] = {"weapon" ,0 ,0 ,0 ,"Garrafra.png", "Equipar"}
items["wbody|WEAPON_CROWBAR"] = {"weapon" ,0 ,0 ,0 ,"pedecabra.png", "Equipar"}
items["wbody|WEAPON_FLASHLIGHT"] = {"weapon" ,0 ,0 ,0 ,"lanterna.png", "Equipar"}
items["wbody|WEAPON_GOLFCLUB"] = {"weapon" ,0 ,0 ,0 ,"tacodegolf.png", "Equipar"}
items["wbody|WEAPON_HAMMER"] = {"weapon" ,0 ,0 ,0 ,"martelo.png", "Equipar"}
items["wbody|WEAPON_HATCHET"] = {"weapon" ,0 ,0 ,0 ,"machado.png", "Equipar"}
items["wbody|WEAPON_KNUCKLE"] = {"weapon" ,0 ,0 ,0 ,"socoingles.png", "Equipar"}
items["wbody|WEAPON_KNIFE"] = {"weapon" ,0 ,0 ,0 ,"faca.png", "Equipar"}
items["wbody|WEAPON_MACHETE"] = {"weapon" ,0 ,0 ,0 ,"machete.png", "Equipar"}
items["wbody|WEAPON_SWITCHBLADE"] = {"weapon" ,0 ,0 ,0 ,"canivete.png", "Equipar"}
items["wbody|WEAPON_NIGHTSTICK"] = {"weapon" ,0 ,0 ,0 ,"cassetete.png", "Equipar"}
items["wbody|WEAPON_WRENCH"] = {"weapon" ,0 ,0 ,0 ,"chavedegrifo.png", "Equipar"}
items["wbody|WEAPON_BATTLEAXE"] = {"weapon" ,0 ,0 ,0 ,"machadodebatalha.png", "Equipar"}
items["wbody|WEAPON_POOLCUE"] = {"weapon" ,0 ,0 ,0 ,"tacodesinuca.png", "Equipar"}
items["wbody|WEAPON_STONE_HATCHET"] = {"weapon" ,0 ,0 ,0 ,"machadodepedra.png", "Equipar"}
items["wbody|WEAPON_PISTOL"] = {"weapon" ,0 ,0 ,0 ,"M1911.png", "Equipar"}
items["wbody|WEAPON_PISTOL_MK2"] = {"weapon" ,0 ,0 ,0 ,"fnfiveseven.png", "Equipar"}
items["wbody|WEAPON_COMBATPISTOL"] = {"weapon" ,0 ,0 ,0 ,"combatpistol.png", "Equipar"}
items["wbody|WEAPON_STUNGUN"] = {"weapon" ,0 ,0 ,0 ,"tazer.png", "Equipar"}
items["wbody|WEAPON_SNSPISTOL"] = {"weapon" ,0 ,0 ,0 ,"hkp7m10.png", "Equipar"}
items["wbody|WEAPON_VINTAGEPISTOL"] = {"weapon" ,0 ,0 ,0 ,"m1922.png", "Equipar"}
items["wbody|WEAPON_REVOLVER"] = {"weapon" ,0 ,0 ,0 ,"magnum44.png", "Equipar"}
items["wbody|WEAPON_MUSKET"] = {"weapon" ,0 ,0 ,0 ,"winchester22.png", "Equipar"}
items["wbody|WEAPON_FLARE"] = {"weapon" ,0 ,0 ,0 ,"sinalizador.png", "Equipar"}
items["wbody|GADGET_PARACHUTE"] = {"weapon" ,0 ,0 ,0 ,"paraquedas.png", "Equipar"}
items["wbody|WEAPON_FIREEXTINGUISHER"] = {"weapon" ,0 ,0 ,0 ,"extintor.png", "Equipar"}
items["wbody|WEAPON_MICROSMG"] = {"weapon" ,0 ,0 ,0 ,"uzi.png", "Equipar"}
items["wbody|WEAPON_SMG"] = {"weapon" ,0 ,0 ,0 ,"MP5.png", "Equipar"}
items["wbody|WEAPON_ASSAULTSMG"] = {"weapon" ,0 ,0 ,0 ,"M-TAR.png", "Equipar"}
items["wbody|WEAPON_COMBATPDW"] = {"weapon" ,0 ,0 ,0 ,"SigSauerMPX.png", "Equipar"}
items["wbody|WEAPON_PUMPSHOTGUN_MK2"] = {"weapon" ,0 ,0 ,0 ,"Remington 870.png", "Equipar"}
items["wbody|WEAPON_PETROLCAN"] = {"weapon" ,0 ,0 ,0 ,"gasolina.png", "Equipar"}
items["wbody|WEAPON_CARBINERIFLE"] = {"weapon" ,0 ,0 ,0 ,"M4A1.png", "Equipar"}
items["wbody|WEAPON_ASSAULTRIFLE"] = {"weapon" ,0 ,0 ,0 ,"ak-103.png", "Equipar"}
items["wbody|WEAPON_GUSENBERG"] = {"weapon" ,0 ,0 ,0 ,"Thompson.png", "Equipar"}

------------------------------Munição-----------------------------------

items["wammo|WEAPON_PISTOL"] = {"ammo" ,0 ,0 ,0 ,"pistol_ammo.png", "Equipar"}
items["wammo|WEAPON_PISTOL_MK2"] = {"ammo" ,0 ,0 ,0 ,"balapequena.png", "Equipar"}
items["wammo|WEAPON_COMBATPISTOL"] = {"ammo" ,0 ,0 ,0 ,"balapequena.png", "Equipar"}
items["wammo|WEAPON_STUNGUN"] = {"ammo" ,0 ,0 ,0 ,"tazer.png", "Equipar"}
items["wammo|WEAPON_SNSPISTOL"] = {"ammo" ,0 ,0 ,0 ,"balapequena.png", "Equipar"}
items["wammo|WEAPON_VINTAGEPISTOL"] = {"ammo" ,0 ,0 ,0 ,"balapequena.png", "Equipar"}
items["wammo|WEAPON_REVOLVER"] = {"ammo" ,0 ,0 ,0 ,"balamedia.png", "Equipar"}
items["wammo|WEAPON_MUSKET"] = {"ammo" ,0 ,0 ,0 ,"balamedia.png", "Equipar"}
items["wammo|WEAPON_FLARE"] = {"ammo" ,0 ,0 ,0 ,"sinalizador.png", "Equipar"}
items["wammo|GADGET_PARACHUTE"] = {"ammo" ,0 ,0 ,0 ,"paraquedas.png", "Equipar"}
items["wammo|WEAPON_FIREEXTINGUISHER"] = {"ammo" ,0 ,0 ,0 ,"extintor.png", "Equipar"}
items["wammo|WEAPON_MICROSMG"] = {"ammo" ,0 ,0 ,0 ,"balapequena.png", "Equipar"}
items["wammo|WEAPON_SMG"] = {"ammo" ,0 ,0 ,0 ,"balamedia.png", "Equipar"}
items["wammo|WEAPON_ASSAULTSMG"] = {"ammo" ,0 ,0 ,0 ,"balasgrandes.png", "Equipar"}
items["wammo|WEAPON_COMBATPDW"] = {"ammo" ,0 ,0 ,0 ,"balasgrandes.png", "Equipar"}
items["wammo|WEAPON_PUMPSHOTGUN_MK2"] = {"ammo" ,0 ,0 ,0 ,"balamedia.png", "Equipar"}
items["wammo|WEAPON_CARBINERIFLE"] = {"ammo" ,0 ,0 ,0 ,"balasgrandes.png", "Equipar"}
items["wammo|WEAPON_ASSAULTRIFLE"] = {"ammo" ,0 ,0 ,0 ,"balasgrandes.png", "Equipar"}
items["wammo|WEAPON_GUSENBERG"] = {"ammo" ,0 ,0 ,0 ,"balasgrandes.png", "Equipar"}
items["wammo|WEAPON_PETROLCAN"] = {"ammo" ,0 ,0 ,0 ,"gasolina.png", "Equipar"}